#ifndef DATASIZES_H
#define DATASIZES_H

#define UID_LEN 6
#define USER_PASSWORD_LEN 8
#define AUCTION_NAME_MAX_LEN 10
#define AUCTION_START_VALUE_LEN 6
#define AUCTION_TIME_ACTIVE_LEN 5
#define AID_MAX_LEN 3
#define ASSET_FILENAME_MAX_LEN 24
#define ASSET_SIZE_MAX_LEN 8
#define DATE_TIME_FORMAT_LEN 19 
#define BID_VALUE_MAX_LEN 6 
#define FILE_SIZE_MAX_LEN 8 // 10MB = 10.000.000 Bytes 
#define MAX_FILE_SIZE 10000000
#define DURATION_LEN 6

#define MAX_RESPONSE_SIZE 3 + 1 + 6 + 1 + UID_LEN + 1 + AUCTION_NAME_MAX_LEN + 1 + ASSET_FILENAME_MAX_LEN + 1 + AUCTION_START_VALUE_LEN + 1 + DATE_TIME_FORMAT_LEN + 1 + AUCTION_TIME_ACTIVE_LEN + 999 * (1 + 1 + 1 + UID_LEN + 1 + BID_VALUE_MAX_LEN + 1 + DATE_TIME_FORMAT_LEN + 1 + DURATION_LEN) + 1 + 1 + DATE_TIME_FORMAT_LEN + 1 + DURATION_LEN + 1 + 1

#define MAX_AID_VALUE 999



#define BUFFER_SIZE 1024
#define IP_LENGTH 39
#define STDARD_SERVER_IP "172.25.224.234"
#define STDARD_SERVER_PORT 58000 + 3

#endif